
/* for home results*/
export const ADD_HOMERESULTS = "ADD_HOMERESULTS";
export const HOMERESULTS_LOADING = "HOMERESULTS_LOADING";
export const HOMERESULTS_FAILED = "HOMERESULTS_FAILED";

/* for explorer results*/
export const ADD_EXPLORER_RESULTS = "ADD_EXPLORER_RESULTS";
export const ADD_EXPLORER_RESULTS_LOADING = "ADD_EXPLORER_RESULTS_LOADING";
export const ADD_EXPLORER_RESULTS_FAILED = "ADD_EXPLORER_RESULTS_FAILED";

/*search results */

/* for search results*/
export const ADD_SEARCH_RESULTS = "ADD_SEARCH_RESULTS";
export const ADD_SEARCH_RESULTS_LOADING = "ADD_SEARCH_RESULTS_LOADING";
export const ADD_SEARCH_RESULTS_FAILED = "ADD_SEARCH_RESULTS_FAILED";

/* for getting user results*/
export const ADD_USER_RESULTS = "ADD_USER_RESULTS";
export const ADD_USER_RESULTS_LOADING = "ADD_USER_RESULTS_LOADING";
export const ADD_USER_RESULTS_FAILED = "ADD_USER_RESULTS_FAILED";


/* for getting random user results*/
export const ADD_RANDOMUSER_RESULTS = "ADD_RANDOMUSER_RESULTS";
export const ADD_RANDOMUSER_RESULTS_LOADING = "ADD_RANDOMUSER_RESULTS_LOADING";
export const ADD_RANDOMUSER_RESULTS_FAILED = "ADD_RANDOMUSER_RESULTS_FAILED";

/* for getting notification results*/
export const ADD_NOTIFICATION_RESULTS = "ADD_NOTIFICATION_RESULTS";
export const ADD_NOTIFICATION_LOADING = "ADD_NOTIFICATION_LOADING";
export const ADD_NOTIFICATION_FAILED = "ADD_NOTIFICATION_FAILED";

/* for getting messages results*/
export const ADD_MESSAGES_RESULTS = "ADD_MESSAGES_RESULTS";
export const ADD_MESSAGES_LOADING = "ADD_MESSAGES_LOADING";
export const ADD_MESSAGES_FAILED = "ADD_MESSAGES_FAILED";
export const ADD_SINGLE_MESSAGES = "ADD_SINGLE_MESSAGES";


/* for getting socket results*/
export const ADD_SOCKET_NOTIFICAITON_RESULTS = "ADD_SOCKET_NOTIFICAITON_RESULTS";

export const ADD_SOCKET_MESSAGE_RESULTS = "ADD_SOCKET_MESSAGE_RESULTS";

export const ADD_SOCKET_CONNECTED = "ADD_SOCKET_CONNECTED";


